# Install script for directory: /home/ubuntu/opencv/modules

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/home/ubuntu/opencv/build_wasm/install")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "Release")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("/home/ubuntu/opencv/build_wasm/modules/.firstpass/js/cmake_install.cmake")
  include("/home/ubuntu/opencv/build_wasm/modules/.firstpass/cudaobjdetect/cmake_install.cmake")
  include("/home/ubuntu/opencv/build_wasm/modules/.firstpass/imgcodecs/cmake_install.cmake")
  include("/home/ubuntu/opencv/build_wasm/modules/.firstpass/ts/cmake_install.cmake")
  include("/home/ubuntu/opencv/build_wasm/modules/.firstpass/flann/cmake_install.cmake")
  include("/home/ubuntu/opencv/build_wasm/modules/.firstpass/world/cmake_install.cmake")
  include("/home/ubuntu/opencv/build_wasm/modules/.firstpass/objdetect/cmake_install.cmake")
  include("/home/ubuntu/opencv/build_wasm/modules/.firstpass/cudaoptflow/cmake_install.cmake")
  include("/home/ubuntu/opencv/build_wasm/modules/.firstpass/videostab/cmake_install.cmake")
  include("/home/ubuntu/opencv/build_wasm/modules/.firstpass/cudaimgproc/cmake_install.cmake")
  include("/home/ubuntu/opencv/build_wasm/modules/.firstpass/superres/cmake_install.cmake")
  include("/home/ubuntu/opencv/build_wasm/modules/.firstpass/highgui/cmake_install.cmake")
  include("/home/ubuntu/opencv/build_wasm/modules/.firstpass/stitching/cmake_install.cmake")
  include("/home/ubuntu/opencv/build_wasm/modules/.firstpass/viz/cmake_install.cmake")
  include("/home/ubuntu/opencv/build_wasm/modules/.firstpass/cudacodec/cmake_install.cmake")
  include("/home/ubuntu/opencv/build_wasm/modules/.firstpass/cudaarithm/cmake_install.cmake")
  include("/home/ubuntu/opencv/build_wasm/modules/.firstpass/videoio/cmake_install.cmake")
  include("/home/ubuntu/opencv/build_wasm/modules/.firstpass/cudabgsegm/cmake_install.cmake")
  include("/home/ubuntu/opencv/build_wasm/modules/.firstpass/calib3d/cmake_install.cmake")
  include("/home/ubuntu/opencv/build_wasm/modules/.firstpass/cudastereo/cmake_install.cmake")
  include("/home/ubuntu/opencv/build_wasm/modules/.firstpass/python/cmake_install.cmake")
  include("/home/ubuntu/opencv/build_wasm/modules/.firstpass/video/cmake_install.cmake")
  include("/home/ubuntu/opencv/build_wasm/modules/.firstpass/cudafeatures2d/cmake_install.cmake")
  include("/home/ubuntu/opencv/build_wasm/modules/.firstpass/cudalegacy/cmake_install.cmake")
  include("/home/ubuntu/opencv/build_wasm/modules/.firstpass/ml/cmake_install.cmake")
  include("/home/ubuntu/opencv/build_wasm/modules/.firstpass/cudafilters/cmake_install.cmake")
  include("/home/ubuntu/opencv/build_wasm/modules/.firstpass/cudawarping/cmake_install.cmake")
  include("/home/ubuntu/opencv/build_wasm/modules/.firstpass/dnn/cmake_install.cmake")
  include("/home/ubuntu/opencv/build_wasm/modules/.firstpass/shape/cmake_install.cmake")
  include("/home/ubuntu/opencv/build_wasm/modules/.firstpass/cudev/cmake_install.cmake")
  include("/home/ubuntu/opencv/build_wasm/modules/.firstpass/java/cmake_install.cmake")
  include("/home/ubuntu/opencv/build_wasm/modules/.firstpass/core/cmake_install.cmake")
  include("/home/ubuntu/opencv/build_wasm/modules/.firstpass/features2d/cmake_install.cmake")
  include("/home/ubuntu/opencv/build_wasm/modules/.firstpass/imgproc/cmake_install.cmake")
  include("/home/ubuntu/opencv/build_wasm/modules/.firstpass/photo/cmake_install.cmake")
  include("/home/ubuntu/opencv/build_wasm/modules/core/cmake_install.cmake")
  include("/home/ubuntu/opencv/build_wasm/modules/imgproc/cmake_install.cmake")
  include("/home/ubuntu/opencv/build_wasm/modules/java_bindings_generator/cmake_install.cmake")
  include("/home/ubuntu/opencv/build_wasm/modules/objdetect/cmake_install.cmake")
  include("/home/ubuntu/opencv/build_wasm/modules/video/cmake_install.cmake")
  include("/home/ubuntu/opencv/build_wasm/modules/dnn/cmake_install.cmake")
  include("/home/ubuntu/opencv/build_wasm/modules/js/cmake_install.cmake")
  include("/home/ubuntu/opencv/build_wasm/modules/python_bindings_generator/cmake_install.cmake")

endif()

