# CMake generated Testfile for 
# Source directory: /home/ubuntu/opencv/modules
# Build directory: /home/ubuntu/opencv/build_wasm/modules
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
subdirs(.firstpass/js)
subdirs(.firstpass/cudaobjdetect)
subdirs(.firstpass/imgcodecs)
subdirs(.firstpass/ts)
subdirs(.firstpass/flann)
subdirs(.firstpass/world)
subdirs(.firstpass/objdetect)
subdirs(.firstpass/cudaoptflow)
subdirs(.firstpass/videostab)
subdirs(.firstpass/cudaimgproc)
subdirs(.firstpass/superres)
subdirs(.firstpass/highgui)
subdirs(.firstpass/stitching)
subdirs(.firstpass/viz)
subdirs(.firstpass/cudacodec)
subdirs(.firstpass/cudaarithm)
subdirs(.firstpass/videoio)
subdirs(.firstpass/cudabgsegm)
subdirs(.firstpass/calib3d)
subdirs(.firstpass/cudastereo)
subdirs(.firstpass/python)
subdirs(.firstpass/video)
subdirs(.firstpass/cudafeatures2d)
subdirs(.firstpass/cudalegacy)
subdirs(.firstpass/ml)
subdirs(.firstpass/cudafilters)
subdirs(.firstpass/cudawarping)
subdirs(.firstpass/dnn)
subdirs(.firstpass/shape)
subdirs(.firstpass/cudev)
subdirs(.firstpass/java)
subdirs(.firstpass/core)
subdirs(.firstpass/features2d)
subdirs(.firstpass/imgproc)
subdirs(.firstpass/photo)
subdirs(core)
subdirs(imgproc)
subdirs(java_bindings_generator)
subdirs(objdetect)
subdirs(video)
subdirs(dnn)
subdirs(js)
subdirs(python_bindings_generator)
